### ISSUE TITLE
One more suggestion

### ISSUE THREAD

**Issue by MaxGraey** [alamusi/wa-test#2]
Instead:
```ts
  while (i < NativeMath.pow(n, 7)) {
    ...
  }
```
I recommend:
```ts
 let end = NativeMath.pow(n, 7); 
 while (i < end) {
    ...
  }
```

AssemblyScript currently can't LICM stdlib calls out of loop during sophisticated optimizations because it should for general case it should analyse side effects for called function but it too big. But JS / Go / Java and etc can do this easily

**Comment by alamusi** [comment]
sharp eyes! I did this intentionally to make the whole loop more computation intensive. on the side note, I did this wrongly in my first version on the python code because of the for loop syntax is different (i.e. for i in range(), which doesn't incur the pow in every loop), and corrected it with a while loop to make the apple to apple comparison.

good point on the LICM part. Is JS/Go/Java compiler able to move the condition out of the loop statement? or for the safety, I should put the pow() explicit inside the loop block?

**Comment by MaxGraey** [comment]
> I should put the pow() explicit inside the loop block?

If you want make loop more complex and also test pow method in all languages than better make some input argument as variant like:
```ts
export function slow64(n: i32): f64 {
  let result = 0.0
  let invN = 1.0 / n;
  let i: i32 = 0
  while (i < n) {
    let x = NativeMath.pow(i * invN, 7);
    result += NativeMath.atan(x) * NativeMath.tan(x)
    i++
  }
  return result
}
```
and done the same for all other langs and tests

**Comment by alamusi** [comment]
updated per your suggestion https://github.com/alamusi/wa-test/commit/423766af99a0e38aef926bffc9618c38b0dc9421

the new math with smaller base in pow() appears to be:

* super in favor of Java (~3x better)
* lighter for python and web-assembly (~30% better)
* somewhat lighter for go (~5% better)
* no change for Javascript

**Comment by MaxGraey** [comment]
thanks! That was to be expected.
